import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Jose Mazhuvanchery Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <link rel="icon" href="/image/favicon.ico" sizes="any"/>
          
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
